# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "C:\Users\Artur\Desktop\Desktop2\vscode mcu\vscode_samd10c14\gsmbase"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "C:\Users\Artur\Desktop\Desktop2\vscode mcu\vscode_samd10c14\gsmbase"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\Artur\Desktop\Desktop2\vscode mcu\vscode_samd10c14\gsmbase\CMakeFiles" "C:\Users\Artur\Desktop\Desktop2\vscode mcu\vscode_samd10c14\gsmbase\CMakeFiles\progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\Artur\Desktop\Desktop2\vscode mcu\vscode_samd10c14\gsmbase\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gsmbase.elf

# Build rule for target.
gsmbase.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 gsmbase.elf
.PHONY : gsmbase.elf

# fast build rule for target.
gsmbase.elf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gsmbase.elf.dir\build.make CMakeFiles/gsmbase.elf.dir/build
.PHONY : gsmbase.elf/fast

#=============================================================================
# Target rules for targets named hex

# Build rule for target.
hex: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 hex
.PHONY : hex

# fast build rule for target.
hex/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hex.dir\build.make CMakeFiles/hex.dir/build
.PHONY : hex/fast

#=============================================================================
# Target rules for targets named lss

# Build rule for target.
lss: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 lss
.PHONY : lss

# fast build rule for target.
lss/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\lss.dir\build.make CMakeFiles/lss.dir/build
.PHONY : lss/fast

src/GSM/GSM.obj: src/GSM/GSM.cpp.obj

.PHONY : src/GSM/GSM.obj

# target to build an object file
src/GSM/GSM.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gsmbase.elf.dir\build.make CMakeFiles/gsmbase.elf.dir/src/GSM/GSM.cpp.obj
.PHONY : src/GSM/GSM.cpp.obj

src/GSM/GSM.i: src/GSM/GSM.cpp.i

.PHONY : src/GSM/GSM.i

# target to preprocess a source file
src/GSM/GSM.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gsmbase.elf.dir\build.make CMakeFiles/gsmbase.elf.dir/src/GSM/GSM.cpp.i
.PHONY : src/GSM/GSM.cpp.i

src/GSM/GSM.s: src/GSM/GSM.cpp.s

.PHONY : src/GSM/GSM.s

# target to generate assembly for a file
src/GSM/GSM.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gsmbase.elf.dir\build.make CMakeFiles/gsmbase.elf.dir/src/GSM/GSM.cpp.s
.PHONY : src/GSM/GSM.cpp.s

src/main.obj: src/main.cpp.obj

.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gsmbase.elf.dir\build.make CMakeFiles/gsmbase.elf.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gsmbase.elf.dir\build.make CMakeFiles/gsmbase.elf.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gsmbase.elf.dir\build.make CMakeFiles/gsmbase.elf.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/peripherals/spi.obj: src/peripherals/spi.cpp.obj

.PHONY : src/peripherals/spi.obj

# target to build an object file
src/peripherals/spi.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gsmbase.elf.dir\build.make CMakeFiles/gsmbase.elf.dir/src/peripherals/spi.cpp.obj
.PHONY : src/peripherals/spi.cpp.obj

src/peripherals/spi.i: src/peripherals/spi.cpp.i

.PHONY : src/peripherals/spi.i

# target to preprocess a source file
src/peripherals/spi.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gsmbase.elf.dir\build.make CMakeFiles/gsmbase.elf.dir/src/peripherals/spi.cpp.i
.PHONY : src/peripherals/spi.cpp.i

src/peripherals/spi.s: src/peripherals/spi.cpp.s

.PHONY : src/peripherals/spi.s

# target to generate assembly for a file
src/peripherals/spi.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gsmbase.elf.dir\build.make CMakeFiles/gsmbase.elf.dir/src/peripherals/spi.cpp.s
.PHONY : src/peripherals/spi.cpp.s

src/peripherals/systick.obj: src/peripherals/systick.c.obj

.PHONY : src/peripherals/systick.obj

# target to build an object file
src/peripherals/systick.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gsmbase.elf.dir\build.make CMakeFiles/gsmbase.elf.dir/src/peripherals/systick.c.obj
.PHONY : src/peripherals/systick.c.obj

src/peripherals/systick.i: src/peripherals/systick.c.i

.PHONY : src/peripherals/systick.i

# target to preprocess a source file
src/peripherals/systick.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gsmbase.elf.dir\build.make CMakeFiles/gsmbase.elf.dir/src/peripherals/systick.c.i
.PHONY : src/peripherals/systick.c.i

src/peripherals/systick.s: src/peripherals/systick.c.s

.PHONY : src/peripherals/systick.s

# target to generate assembly for a file
src/peripherals/systick.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gsmbase.elf.dir\build.make CMakeFiles/gsmbase.elf.dir/src/peripherals/systick.c.s
.PHONY : src/peripherals/systick.c.s

src/peripherals/uart.obj: src/peripherals/uart.cpp.obj

.PHONY : src/peripherals/uart.obj

# target to build an object file
src/peripherals/uart.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gsmbase.elf.dir\build.make CMakeFiles/gsmbase.elf.dir/src/peripherals/uart.cpp.obj
.PHONY : src/peripherals/uart.cpp.obj

src/peripherals/uart.i: src/peripherals/uart.cpp.i

.PHONY : src/peripherals/uart.i

# target to preprocess a source file
src/peripherals/uart.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gsmbase.elf.dir\build.make CMakeFiles/gsmbase.elf.dir/src/peripherals/uart.cpp.i
.PHONY : src/peripherals/uart.cpp.i

src/peripherals/uart.s: src/peripherals/uart.cpp.s

.PHONY : src/peripherals/uart.s

# target to generate assembly for a file
src/peripherals/uart.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gsmbase.elf.dir\build.make CMakeFiles/gsmbase.elf.dir/src/peripherals/uart.cpp.s
.PHONY : src/peripherals/uart.cpp.s

src/startup_samd10.obj: src/startup_samd10.c.obj

.PHONY : src/startup_samd10.obj

# target to build an object file
src/startup_samd10.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gsmbase.elf.dir\build.make CMakeFiles/gsmbase.elf.dir/src/startup_samd10.c.obj
.PHONY : src/startup_samd10.c.obj

src/startup_samd10.i: src/startup_samd10.c.i

.PHONY : src/startup_samd10.i

# target to preprocess a source file
src/startup_samd10.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gsmbase.elf.dir\build.make CMakeFiles/gsmbase.elf.dir/src/startup_samd10.c.i
.PHONY : src/startup_samd10.c.i

src/startup_samd10.s: src/startup_samd10.c.s

.PHONY : src/startup_samd10.s

# target to generate assembly for a file
src/startup_samd10.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gsmbase.elf.dir\build.make CMakeFiles/gsmbase.elf.dir/src/startup_samd10.c.s
.PHONY : src/startup_samd10.c.s

src/syscalls.obj: src/syscalls.c.obj

.PHONY : src/syscalls.obj

# target to build an object file
src/syscalls.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gsmbase.elf.dir\build.make CMakeFiles/gsmbase.elf.dir/src/syscalls.c.obj
.PHONY : src/syscalls.c.obj

src/syscalls.i: src/syscalls.c.i

.PHONY : src/syscalls.i

# target to preprocess a source file
src/syscalls.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gsmbase.elf.dir\build.make CMakeFiles/gsmbase.elf.dir/src/syscalls.c.i
.PHONY : src/syscalls.c.i

src/syscalls.s: src/syscalls.c.s

.PHONY : src/syscalls.s

# target to generate assembly for a file
src/syscalls.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gsmbase.elf.dir\build.make CMakeFiles/gsmbase.elf.dir/src/syscalls.c.s
.PHONY : src/syscalls.c.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... hex
	@echo ... lss
	@echo ... gsmbase.elf
	@echo ... src/GSM/GSM.obj
	@echo ... src/GSM/GSM.i
	@echo ... src/GSM/GSM.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/peripherals/spi.obj
	@echo ... src/peripherals/spi.i
	@echo ... src/peripherals/spi.s
	@echo ... src/peripherals/systick.obj
	@echo ... src/peripherals/systick.i
	@echo ... src/peripherals/systick.s
	@echo ... src/peripherals/uart.obj
	@echo ... src/peripherals/uart.i
	@echo ... src/peripherals/uart.s
	@echo ... src/startup_samd10.obj
	@echo ... src/startup_samd10.i
	@echo ... src/startup_samd10.s
	@echo ... src/syscalls.obj
	@echo ... src/syscalls.i
	@echo ... src/syscalls.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

